apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
    containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: local-persistent-storage
        mountPath: /var/www/html
    volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: local-pvc
