---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
  - host: tra.monlog.ir
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik
          servicePort: 8100
